version: "3.8"
services:
  api-server:
    build: ./
    ports: 
          - 3000:3000
  db:
    image: postgis/postgis:12-3.4
    command: postgres -c max_connections=1000
    container_name: as-db
    environment:
            POSTGRES_DB: as-db
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
    ports:
          - 8000:8000