CREATE SCHEMA IF NOT EXISTS cpo;
SET SCHEMA 'cpo';

---- users ----
CREATE TABLE IF NOT EXISTS users (
	uuid UUID NOT NULL,
	email VARCHAR NOT NULL,
	client_id VARCHAR NOT NULL,
	locale VARCHAR(5) DEFAULT NULL,
	name VARCHAR(30) DEFAULT NULL,
	phone VARCHAR(15) DEFAULT NULL,
	birthday DATE DEFAULT NULL,
	profile_picture_url VARCHAR DEFAULT NULL,
	ioep_access_token VARCHAR DEFAULT NULL,
	ioep_access_expired_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT NULL,
    ioep_refresh_token VARCHAR DEFAULT NULL,
    ioep_refresh_expired_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT NULL,
	created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
	CONSTRAINT users_pkey PRIMARY KEY (uuid)
);
